### PR TITLE
Fixes the `@ExceptionHandler` cannot work problem.

### LINKED ISSUE #147: When use `@ExceptionHandler`, exception occurred when start the application.
### Expected behavior
work normal

### Actual behavior
```
org.springframework.beans.factory.BeanCreationException: Failed to start Restlight server.; nested exception is java.util.concurrent.ExecutionException: java.lang.NullPointerException: underlying

	at io.esastack.restlight.starter.ServerStarter.afterSingletonsInstantiated(ServerStarter.java:99)
	at io.esastack.restlight.integration.test.BaseIntegrationTest.setUp(BaseIntegrationTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: underlying
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at io.esastack.restlight.starter.ServerStarter.afterSingletonsInstantiated(ServerStarter.java:95)
	... 18 more
Caused by: java.lang.NullPointerException: underlying
	at esa.commons.Checks.checkNotNull(Checks.java:52)
	at io.esastack.restlight.core.configure.DelegatingDeployContext.<init>(DelegatingDeployContext.java:46)
	at io.esastack.restlight.core.handler.impl.HandlerContext.<init>(HandlerContext.java:41)
	at io.esastack.restlight.springmvc.resolver.exception.SpringMvcExceptionResolverFactory.lambda$extractExceptionHandlers$0(SpringMvcExceptionResolverFactory.java:120)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.esastack.restlight.springmvc.resolver.exception.SpringMvcExceptionResolverFactory.extractExceptionHandlers(SpringMvcExceptionResolverFactory.java:119)
	at io.esastack.restlight.springmvc.resolver.exception.SpringMvcExceptionResolverFactory.extractMappings(SpringMvcExceptionResolverFactory.java:109)
	at io.esastack.restlight.springmvc.resolver.exception.SpringMvcExceptionResolverFactory.createMappersFromControllerAdvice(SpringMvcExceptionResolverFactory.java:91)
	at io.esastack.restlight.core.resolver.exception.AbstractExceptionResolverFactory.initControllerAdviceToExceptionHandlerBean(AbstractExceptionResolverFactory.java:93)
	at io.esastack.restlight.core.resolver.exception.AbstractExceptionResolverFactory.init(AbstractExceptionResolverFactory.java:61)
	at io.esastack.restlight.core.resolver.exception.AbstractExceptionResolverFactory.<init>(AbstractExceptionResolverFactory.java:39)
	at io.esastack.restlight.springmvc.resolver.exception.SpringMvcExceptionResolverFactory.<init>(SpringMvcExceptionResolverFactory.java:57)
	at io.esastack.restlight.springmvc.spi.SpringMvcExceptionResolverFactoryProvider.factory(SpringMvcExceptionResolverFactoryProvider.java:38)
	at io.esastack.restlight.core.Deployments.registerRoutes(Deployments.java:1115)
	at io.esastack.restlight.core.Deployments.createRestlightHandler(Deployments.java:1619)
	at io.esastack.restlight.core.Deployments.doGetRestlightHandler(Deployments.java:1036)
	at io.esastack.restlight.core.Deployments.getRestlightHandler(Deployments.java:1611)
	at io.esastack.restlight.core.Deployments.applyDeployments(Deployments.java:1606)
	at io.esastack.restlight.core.AbstractRestlight.buildServer(AbstractRestlight.java:216)
	at io.esastack.restlight.core.AbstractRestlight.start(AbstractRestlight.java:198)
	at io.esastack.restlight.server.bootstrap.AbstractDelegatedRestlightServer.start(AbstractDelegatedRestlightServer.java:34)
	at io.esastack.restlight.starter.ServerStarter.lambda$afterSingletonsInstantiated$0(ServerStarter.java:86)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

```

### Steps to reproduce
1.add customize exceptionHandler like below.
```java
@ControllerAdvice
public class CustomExceptionHandler {

    @ExceptionHandler(CustomException.class)
    public String handleCustomException(CustomException customException, HttpResponse httpResponse) {
        httpResponse.status(HttpStatus.UNAUTHORIZED.code());
        return customException.getMessage();
    }
}
```
2.start the application.

### Env
- Restlight version: 1.0.0-SNAPSHOT
- JVM version: 1.8
- OS:Windows 10

### PR DESCRIPTION
**Pull request by brotherlu-xcq**
Motivation:

- Fixes the `@ExceptionHandler` cannot work problem.
- Fixes the unit test problem.

Modification:

- for the exception param return the null resolver
- fix the jackson time serialize unit test problem.

Result:

Fixes #147

### CODE REVIEW

File: restlight-core/src/main/java/io/esastack/restlight/core/handler/impl/HandlerMethodAdapter.java [hunk 1]
```diff
@@ -108,6 +109,10 @@ private ResolvableParam<MethodParam, ResolverWrap>[] buildParamResolvers(Handler
 
     <P extends Param> ResolvableParam<P, ResolverWrap> getResolverWrap(P param,
                                                                        HandlerResolverFactory factory) {
+        // check if we need a resolver here
+        if (isNullResolver(param, factory)) {
+            return new ResolvableParam<>(param, null);
+        }
```
Comment (LCDZhao-Z) [inline restlight-core/src/main/java/io/esastack/restlight/core/handler/impl/HandlerMethodAdapter.java:115]: The meaning of this code is a little obscure.

**Review by LCDZhao-Z — APPROVED** [review]
