### PR TITLE
fix: fast return when match media type (#79)

### LINKED ISSUE #79: mediaType matching order
### Expected behavior
when accpet is blank or */*, return first match support media type serializer

### Actual behavior 
return the last 

### Steps to reproduce
image
no Accept
excepted json format but protostuff

### Env
- Restlight version: 0.1.1

### PR DESCRIPTION
**Pull request by Jia-shuaitao**
Closes #79

### CODE REVIEW

File: restlight-core/src/main/java/esa/restlight/core/resolver/result/AbstractResponseBodyReturnValueResolver.java [hunk 1]
```diff
@@ -103,6 +104,9 @@ public int getOrder() {
                             break;
                         }
                     }
+                    if (Objects.nonNull(serializer)) {
+                        break;
+                    }
```
Comment (alalag1) [inline restlight-core/src/main/java/esa/restlight/core/resolver/result/AbstractResponseBodyReturnValueResolver.java:109]: just break with a label for the outer loop like
```java
outerloop:
for (int i=0; i < 5; i++) {
    for (int j=0; j < 5; j++) {
        if (i * j > 6) {
            break outerloop;
        }
    }
}
```

**Review by alalag1 — CHANGES_REQUESTED** [review]

File: restlight-core/src/main/java/esa/restlight/core/resolver/result/AbstractResponseBodyReturnValueResolver.java (hunk 1 above)
Comment (Jia-shuaitao) [reply restlight-core/src/main/java/esa/restlight/core/resolver/result/AbstractResponseBodyReturnValueResolver.java]: amazing!!!  I almost forget this usage;  This also resolve my  recent problem that how to simple break multi loop1

**Comment by alalag1** [comment]
thx a lot! @Jia-shuaitao
